### PR TITLE
Improve performance of windows rendering by using a buffer

### PR DESCRIPTION
**Pull request by sylvainmouquet**
Hi,

I have developed this functionnality for the project glances

Thanks

### CODE REVIEW

**Comment by pywkm** [comment]
Sylvain, thanks for adding UTF-8 support in Windows console. I missed it. :-).

Shouldn't second line look like: "# -*- coding utf-8 -*-"? (added dash between "utf" and "8"). I couldn't even run those three new files without SyntaxError, until I added this dash.

Second issue. Well, it seems that I rejoiced to early ;-), because displaying UTF8 characters works fine in "termianl_buffer.py" demo - yes, but it doesn't work in "terminal.py" demo:
"""
Traceback (most recent call last):
  File "H:\Pobrane\colorconsole-master\colorconsole\terminal.py", line 106, in <module>
    test()
  File "H:\Pobrane\colorconsole-master\colorconsole\terminal.py", line 72, in test
    print(u"UTF8 é\xe0@\xe8\xf9")
  File "C:\Python34\lib\encodings\cp852.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe0' in position 6: character maps to <undefined>
"""
Which is standard error, when I try to print UTF8 character in my console (without setting code page to UTF8 - but demo from "terminal_buffer.py" worked fine without this setting. Also, setting code page to 65001 never solved issue with wrongly displayed characters - for instance I get something like "UTF8 éà@èùèùù�" instead of "UTF8 éà@èù" in your demo with print and print_at functions. With set_buffer_string and print_buffer methods it looks OK, either with codepage 852 or 65001). 
Do you know why this doesn't work on my computer?
Wiktor

**Comment by sylvainmouquet** [comment]
HI Wiktor,

What version of python do you use?
You could take a look on it https://wiki.python.org/moin/PrintFails

Sylvain

**Comment by lskbr** [comment]
Hi sylvainmouquet, thanks for the patch! I already applied some of your suggestions.
As the objective of this module is to provide common code to Linux, Windows and Mac OS X; I hesitate to commit the buffered mode, but I think it is a nice idea. Let me think about how to better integrate your contribution into the project. I think it would be great to have a save screen and restore screen like in old dos mode... I'm thinking about shadows now ;-D The set title bug is already fixed on my last commit, thanks again.

Regarding utf-8 support, it is a mess on Python 2.x for Windows. I tested the code with codepage 850 and 65001. The latest version of Python 2.7.9 really doesn't like it. I had no problems with Python 3.4.2. I replaced Python print function by a direct call to WriteConsoleW. It is working fine for me on CP850 and CP65001.

Hi pywkm, the error you described (this odd char in the end of the string) comes from the Python print function on Windows. It only happens with Python 2.x. The new version I just committed is working better.

Although, the buffered mode is not yet integrated, we still have flickering, but I will add this enhancement in a future version.

Please, let me know if you have any problems with the latest commit. If it is ok, I will upload a new package to pypi.

**Comment by pywkm** [comment]
Oh, sorry, I forgot to mention. I was testing this in Python 3.4.1. I'll try to upgrade to 3.4.2 and check it again.
Wiktor

**Comment by sylvainmouquet** [comment]
Hi lskbr 

Yes i think my implementation is not well integrated in the project.
A save & restore screen could be seen like a canvas (html5 canvas & cairo use this mechanism)
Another idea is to add a multi-layers system to create nested popup and more (addLayer, removeLayer)

Hi pywkm 
I use python 3.4.2 and python 2.7.9 on Windows 8 64 bits and it is correct on the twice.

**Comment by pywkm** [comment]
Upgrading to Python 3.4.2 didn't help. It behaves the same with CP852 (UnicodeEncodeError) and with CP65001 (extra chars at the end of unicode string)

@lskbr 
If you're testing this code with provided characters - it will work, because CP850 actually knows how to show `éàèù` http://pl.wikipedia.org/wiki/CP850. CP852 doesn't know http://pl.wikipedia.org/wiki/CP852 so it fails. So what I'm saying is when I change code page to 850, provided test also works for me. But it still won't work with characters, that I would like to use, like `╘╖` or `♠♥♦♣` - check with those characters and CP850. They work with `terminal_buffer.py` though. I'm not as smart as you guys, so I don't understand why it works with buffer.

But I still don't know why it doesn't work with CP65001 set in console. Maybe it's something that MS improved in Win8? @lskbr - you also have the newest Windows OS? Maybe it's Win7 that fails here. 

Wiktor

**Comment by sylvainmouquet** [comment]
What is the result of :
```
import sys
print(sys.getdefaultencoding())  
print(sys.stdout.encoding)  
print("éè@ù")
```
i have this result
```
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.getdefaultencoding())  
ascii
>>> print(sys.stdout.encoding)  
UTF-8
>>> print("éè@ù")
éè@ù 
```

**Comment by pywkm** [comment]
<pre>
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.getdefaultencoding())
utf-8
>>> print(sys.stdout.encoding)
cp852
>>> print("@")   # well it's strange, but I can't paste this text to my console (this is what I get after pasting), or write them in my PL keyboard settings
@
>>> print("\u00E9")
é
>>> print("\u00E8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\encodings\cp852.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 0: character maps to <undefined>
>>> print("\u00F9")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\encodings\cp852.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf9' in position 0: character maps to <undefined>
>>>
</pre>

After changing to 65001 code page (Windows' UTF-8, I guess):
<pre>
E:\>chcp 65001
Aktywna strona kodowa: 65001

E:\>py -3
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:16:31) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.getdefaultencoding())
utf-8
>>> print(sys.stdout.encoding)
cp65001
>>> print("@")  # the same - pasting doesn't work
@
>>> print("\u00E9")
é

>>> print("\u00E8")
è

>>> print("\u00F9")
ù

>>>
</pre>

Those extra blank lines after properly displayed characters mean, that there's something ugly attached to this output. :-) This tail gets longer (and more visible), the longer this unicode string is. For example (still in CP65001):
<pre>
>>> print("\u00E9\u00E8\u00F9")
éèù
�
>>> print("\u00E9\u00E8\u00F9\u00E9\u00E8\u00F9\u00E9\u00E8\u00F9")
éèùéèùéèù
�éèù
�
>>>
</pre>

**Comment by pywkm** [comment]
Oh, and one more output from Python 2. So, problem with pasting into console wasn't connected with console itself, but with Python 3 REPL, because in Py2 I can paste this string.
<pre>
E:\>chcp 852
Aktywna strona kodowa: 852

E:\>py
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.getdefaultencoding())
ascii
>>> print(sys.stdout.encoding)
cp852
>>> print("éè@ù")
éc@u
>>>
</pre>

Interesting result after changing code page to 65001:
<pre>
E:\>chcp 65001
Aktywna strona kodowa: 65001

E:\>py
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys

LookupError: unknown encoding: cp65001
>>> print("éè@ù")


E:\>
</pre>
Notice that it returned to command line prompt.

Wiktor

**Comment by pywkm** [comment]
@lskbr 
I didn't notice your latest commit, and that you ask for opinions. Sorry.

It does work great. But bear in mind, that I'm novice programmer and I have (well, still creating) only one program that uses colorconsole package. So I'm not using/testing all features.

It does work now with UTF-8 characters, and I can now use all those characters that I mentioned earlier, which is great, because now I can display my window's borders the way I planned many months ago:
<pre>
┌────────╖
│ Start  ║
│ Zmiana ║
│ Anuluj ║
╘════════╝
</pre>
(well, it really does look better in console - all is aligned :-))

With version 0.7 of colorconsole I couldn't display above in Win7 console, so I compromised and used this look:
<pre>
╔════════╗
║ Start  ║
║ Zmiana ║
║ Anuluj ║
╚════════╝
</pre>
Now I can come back to my original idea. Thanks. ;-)
Wiktor

**Comment by lskbr** [comment]
Hi @pywkm,

Nice that it worked for you. I already tested on my side, this new version looks like a candidate for 0.7.2. I think I will clean up some dead code on it and maybe refactor some code on the main module. I already started to think about the new module with multiple windows and the buffered output. Please let me know if you find any problems.

**Comment by sylvainmouquet** [comment]
any news?

**Comment by lskbr** [comment]
Hi @sylvainmouquet , it would be nice to merge our modules or create a new one. I didn't have time to check a portable solution, yet. It would help a lot if you had a list of desired features. I'm thinking also in adding controls to the text screen, making easier to have inputs like in DOS times :-D
Simple text form are almost impossible (if you need cross platform) today.
I really miss some text effects we had on DOS, like shadows, but I'm afraid to re-implement curses.

**Pull request closed without merging**
